// -i- Automatically generated by 'yarn link-routes', do not modify manually
export const routeManifest = {
  ['/author']: 'AuthorScreen',
  ['/']: 'HomeScreen',
} as const

// eslint-disable-next-line @typescript-eslint/ban-types
export type KnownRoutes = keyof typeof routeManifest | (string & {})
