#!/usr/bin/env node --experimental-specifier-resolution=node
import path from 'path'
import fs from 'fs'
import { fileURLToPath } from 'node:url'
import { loadFilesSync } from '@graphql-tools/load-files'
import { mergeTypeDefs } from '@graphql-tools/merge'
import { print } from 'graphql'

/* --- Constants ------------------------------------------------------------------------------- */

const currentDir = path.dirname(fileURLToPath(import.meta.url))
const schemaPath = path.resolve(currentDir, '../../../features/@app-core/graphql', 'schema.graphql')
const typeDefsPath = path.resolve(currentDir, '../../../features/@app-core/graphql', 'typeDefs.ts')

const disclaimer = `-i- This file was generated by the 'build-graphql-schema' script. Don't modify it manually.\n`

const CUSTOM_SCALARS = ['scalar Date', 'scalar JSON', 'scalar JSONObject'] as const

/** --- createSchemaDefinitions() -------------------------------------------------------------- */
/** -i- Combine all custom and other (e.g. generated) .graphql schema definitions */
export const createSchemaDefinitions = () => {
    const rootDir = path.resolve(currentDir, '../../..')
    const schemaPathPattern = `${rootDir}/(features|packages)/**/!(schema).graphql`
    const customGraphQLDefinitions = loadFilesSync(schemaPathPattern)
    return mergeTypeDefs([
        ...CUSTOM_SCALARS,
        ...customGraphQLDefinitions,
        /* TODO: Support other custom typedefs? */
    ])
}

/* --- Script ---------------------------------------------------------------------------------- */

const buildSchemaDefinitions = async () => {
    const schemaDefinitions = createSchemaDefinitions()
    const typeDefsString = print(schemaDefinitions)
    fs.writeFileSync(schemaPath, `## ${disclaimer}\n${typeDefsString}\n`)
    fs.writeFileSync(typeDefsPath, `// ${disclaimer}\nexport const typeDefs = \`${typeDefsString}\`\n`)
}

buildSchemaDefinitions()
