"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LI = exports.UL = exports.Time = exports.TR = exports.THead = exports.TH = exports.TFoot = exports.TD = exports.TBody = exports.Table = exports.Strong = exports.Section = exports.S = exports.Q = exports.Pre = exports.P = exports.Nav = exports.Mark = exports.Main = exports.I = exports.HR = exports.Header = exports.H6 = exports.H5 = exports.H4 = exports.H3 = exports.H2 = exports.H1 = exports.Footer = exports.EM = exports.Del = exports.Code = exports.Caption = exports.BR = exports.BlockQuote = exports.B = exports.Aside = exports.Article = exports.A = void 0;
var html_elements_1 = require("@expo/html-elements");
var core_1 = require("../core");
var navigation_1 = require("../navigation");
Object.defineProperty(exports, "A", { enumerable: true, get: function () { return navigation_1.AetherLink; } });
/* --- HTML Elements --------------------------------------------------------------------------- */
// -i- Superset of @expo/html-elements for SEO, aetherspace & web friendly alternative primitives
// -i- See https://github.com/expo/expo/tree/master/packages/html-elements#components
// -i- Renders as semantic HTML on web & server, but as Text / View / etc. on mobile
// -i- Bringing the power of tailwind 'tw' prefixes & media query support to web
var AetherArticle = core_1.aetherify(html_elements_1.Article)();
exports.Article = AetherArticle;
var AetherAside = core_1.aetherify(html_elements_1.Aside)();
exports.Aside = AetherAside;
var AetherB = core_1.aetherify(html_elements_1.B)();
exports.B = AetherB;
var AetherBlockQuote = core_1.aetherify(html_elements_1.BlockQuote)();
exports.BlockQuote = AetherBlockQuote;
var AetherBR = core_1.aetherify(html_elements_1.BR)();
exports.BR = AetherBR;
var AetherCaption = core_1.aetherify(html_elements_1.Caption)();
exports.Caption = AetherCaption;
var AetherCode = core_1.aetherify(html_elements_1.Code)();
exports.Code = AetherCode;
var AetherDel = core_1.aetherify(html_elements_1.Del)();
exports.Del = AetherDel;
var AetherEM = core_1.aetherify(html_elements_1.EM)();
exports.EM = AetherEM;
var AetherFooter = core_1.aetherify(html_elements_1.Footer)();
exports.Footer = AetherFooter;
var AetherH1 = core_1.aetherify(html_elements_1.H1)();
exports.H1 = AetherH1;
var AetherH2 = core_1.aetherify(html_elements_1.H2)();
exports.H2 = AetherH2;
var AetherH3 = core_1.aetherify(html_elements_1.H3)();
exports.H3 = AetherH3;
var AetherH4 = core_1.aetherify(html_elements_1.H4)();
exports.H4 = AetherH4;
var AetherH5 = core_1.aetherify(html_elements_1.H5)();
exports.H5 = AetherH5;
var AetherH6 = core_1.aetherify(html_elements_1.H6)();
exports.H6 = AetherH6;
var AetherHeader = core_1.aetherify(html_elements_1.Header)();
exports.Header = AetherHeader;
var AetherHR = core_1.aetherify(html_elements_1.HR)();
exports.HR = AetherHR;
var AetherI = core_1.aetherify(html_elements_1.I)();
exports.I = AetherI;
var AetherMain = core_1.aetherify(html_elements_1.Main)();
exports.Main = AetherMain;
var AetherMark = core_1.aetherify(html_elements_1.Mark)();
exports.Mark = AetherMark;
var AetherNav = core_1.aetherify(html_elements_1.Nav)();
exports.Nav = AetherNav;
var AetherP = core_1.aetherify(html_elements_1.P)();
exports.P = AetherP;
var AetherPre = core_1.aetherify(html_elements_1.Pre)();
exports.Pre = AetherPre;
var AetherQ = core_1.aetherify(html_elements_1.Q)();
exports.Q = AetherQ;
var AetherS = core_1.aetherify(html_elements_1.S)();
exports.S = AetherS;
var AetherSection = core_1.aetherify(html_elements_1.Section)();
exports.Section = AetherSection;
var AetherStrong = core_1.aetherify(html_elements_1.Strong)();
exports.Strong = AetherStrong;
var AetherTable = core_1.aetherify(html_elements_1.Table)();
exports.Table = AetherTable;
var AetherTBody = core_1.aetherify(html_elements_1.TBody)();
exports.TBody = AetherTBody;
var AetherTD = core_1.aetherify(html_elements_1.TD)();
exports.TD = AetherTD;
var AetherTFoot = core_1.aetherify(html_elements_1.TFoot)();
exports.TFoot = AetherTFoot;
var AetherTH = core_1.aetherify(html_elements_1.TH)();
exports.TH = AetherTH;
var AetherTHead = core_1.aetherify(html_elements_1.THead)();
exports.THead = AetherTHead;
var AetherTR = core_1.aetherify(html_elements_1.TR)();
exports.TR = AetherTR;
var AetherTime = core_1.aetherify(html_elements_1.Time)();
exports.Time = AetherTime;
var AetherUL = core_1.aetherify(html_elements_1.UL)();
exports.UL = AetherUL;
var AetherLI = core_1.aetherify(html_elements_1.LI)();
exports.LI = AetherLI;
